### ISSUE TITLE
Dropbear - i can not ssh the device

### ISSUE THREAD

**Issue by sherifomran** [agherzan/meta-raspberrypi#230]
After installing RPI 0 W using Meta-raspberry pi, i can not SSH the device, it seems there are some ports disabled or so. 

**Description**

I installed a new image and i am trying to use it from another computer due to a missing keyboard, i tried to ssh the device but i can not connect to it. It seems there are some ports closed. Do we need to add other packages to it? or do extra configurations? 
I have sysVinit installed and not systemd.

**Steps to reproduce the issue:**
bitbake rpi-basic-image

**Comment by agherzan** [comment]
@sherifomran Did you try what was recommended above?

**Comment by Manyyack** [comment]
ssh doesn't work for me when I do 'core-image-base' but working on rpi-basic-image

**Comment by agherzan** [comment]
@Manyyack `rpi-basic-image` is deprecated. You can define your own image and include `ssh-server-dropbear`. Indeed `core-image-base` doesn't do that and it is not supposed to either. Yocto provides all the tools needed to define your own image based on your needs.

Closing this as it looks like a configuration issue. We will reopen if proven otherwise.
