### ISSUE TITLE
KERNEL_DEVICETREE cannot be extended

### ISSUE THREAD

**Issue by nandra** [agherzan/meta-raspberrypi#300]
I'm trying to add more dtbo to final image by specifying in linux-raspberrypi.bbappend or in local.conf by extending KEREL_DEVICETREE += "overlays/pwm.dtbo" but looks like when specify it in local.conf variable KERNEL_DEVICETREE is overwritten or when specify it in linux-raspberrypi.bbeappend it have no effect. Any ideas how to extend this variable to get more dtbo's on target? I workarounded it by extending variable in rpi-base.conf (but I would like to avoid that ;) ) Thanks.

**Comment by agherzan** [comment]
Hi @nandra . Have you tried appending? We are doing something similar here: https://github.com/resin-os/resin-raspberrypi/blob/master/layers/meta-resin-raspberrypi/conf/layer.conf#L17. Appending using `_append`.

**Comment by nandra** [comment]
I tried += also _append but it doesn't work. I'll re-check and report status (maybe my env gets broken somehow). Thanks.

**Comment by nandra** [comment]
OK with _append it work which is quite strange because I assume that += also should work. Anyway when looking in rpi-base.inc we have 
```
KERNEL_DEVICETREE ?= " \

```
so softval is used while in 
raspberrypi3-64.conf there is:
```
KERNEL_DEVICETREE = " \
```

So maybe this could be a problem that when user want to add something to KERNEL_DEVICETREEE for non 64bit rpi then it cannot be overwritten? Thanks.

**Comment by aswild** [comment]
- `local.conf` is parsed before the `${MACHINE}.conf`, so any sets with = in a machine (or distro) config will override `local.conf`
- Using += will clobber a default set with ?= (I'm not sure why bitbake behaves this way, but it does)
- Using _append should work around both of these (because _append is treated like an override and processed at the end of variable expansion)
- You need to modify KERNEL_DEVICETREE in a .conf file, not by bbappending the kernel recipe, because KERNEL_DEVICETREE is used in multiple recipes (the kernel but also the image recipes via sdcard_image-rpi.bbclass)

**Comment by nandra** [comment]
@aswild thanks for detailed description. I think we can close this issue as _append works as expected. Thanks.
