### ISSUE TITLE
Zero W WiFi not working

### ISSUE THREAD

**Issue by MeantCoder** [agherzan/meta-raspberrypi#308]
Hello,

I'm compiled Yocto with linux-firmware-bcm43430 and distro feature wifi enabled but i can't use wifi on zero w.

iw list output : nl80211 not found.

**Comment by nandra** [comment]
Looks like /lib/firmware is empty in final image (using sumo branch)

**Comment by nandra** [comment]
I didn't have time to look on issue (why MACHINE_RRECOMENDS doesn't put firmware to rootfs). Anyway workaround is to add:
```
linux-firmware-bcm43430 \
linux-firmware-bcm43430a1-hcd \
```

to e.g. IMAGE_INSTALL (works for raspberrypi0-wifi only)

**Comment by mirzak** [comment]
Did you mean MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS?

Which image did you build, because that will determinate if `MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS` is included or not.

Basically the image must inherit from "core-image"for the above to be included.

**Comment by nandra** [comment]
Nope I mean this one: https://github.com/agherzan/meta-raspberrypi/blob/2d40b000021bc8a9ef7f329ed0ad410f8d227b97/conf/machine/raspberrypi0-wifi.conf#L9

I build custom image (also core-image-minimal) and my custom image inherit core-image.

**Comment by mirzak** [comment]
`core-image-minimal` will definitely not install `MACHINE_EXTRA_RRECOMMENDS`, even though it inherits `core-image.bbclass` it overrides the `IMAGE_INSTALL`

It looks like `MACHINE_EXTRA_RRECOMMENDS` is installed trough `packagegroup-base` which is is install by `core-image.bbclass` by including the `packagegroup-base-extended`.

Does your custom image "override" `IMAGE_INSTALL` or does it append to it. Because the logic in `core-image.bbclass` is:

```
CORE_IMAGE_BASE_INSTALL = '\
    packagegroup-core-boot \
    packagegroup-base-extended \
    \
    ${CORE_IMAGE_EXTRA_INSTALL} \
    '

CORE_IMAGE_EXTRA_INSTALL ?= ""

IMAGE_INSTALL ?= "${CORE_IMAGE_BASE_INSTALL}"
```

This means that if you have a `IMAGE_INSTALL = "something"` in your custom image then the base package-groups will not be installed.

Try building `core-image-base`.

**Comment by nandra** [comment]
You're right @mirzak . I had in custom image IMAGE_INSTALL = instead of IMAGE_INSTALL +=
@MeantCoder can you please verify if you have /lib/firmware directory in your target? Thanks.

**Comment by agherzan** [comment]
@mirzak has the right and detailed answer here. I'll close this issue as this should bring the needed firmware in the image.
