### ISSUE TITLE
Generic raspberry image

### ISSUE THREAD

**Issue by thknx** [agherzan/meta-raspberrypi#381]
How can I build generic-raspberry yocto image which be able to work all raspberry boards? Everytime I have to change MACHINE parameter on yocto but I want to build a generic image like raspbian which consists necessery drivers and firmwares?

Can you advice me please?

**Comment by kraj** [comment]
There is no pre-cooked recipe for that, you can create a new image from `MACHINE="raspberrypi"` and then add all firmwares into image. You also might need to package all kernel configs and DTBO for all machines into this jumbo image.

**Comment by thknx** [comment]
I thought may be Mr. @agherzan help me because I have not knowledge about tuning on arm&rpi.

**Comment by agherzan** [comment]
As Khem said above, we don't have this implemented at this point. I recommend defining a new machine and start building up all the needed bits (dtbs, firmware etc). The only thing you need to pay extra care to is the kernel image filename because that is machine specific (actually arch specific). So you will have to provide all the needed ones - kernel7, kernel and kernel8.
