### ISSUE TITLE
Raspberry Pi CM4 not booting with U-Boot

### ISSUE THREAD

**Issue by havok13888** [agherzan/meta-raspberrypi#846]
![image](https://user-images.githubusercontent.com/1217312/114739971-0510f600-9d0f-11eb-875b-527219722602.png)

Image with RPI_USE_U_BOOT = "0" build and boots successfully on the PI4B and CM4. 
Image with RPI_USE_U_BOOT = "1" build and boots successfully on the PI4B. It does not boot with a CM4. 

Using default boot script with latest gatesgarth. Machine conf: raspberrypi4

![image](https://user-images.githubusercontent.com/1217312/114740394-6d5fd780-9d0f-11eb-91bf-fbdc6caacee0.png)

**Comment by thomas-at-rock7** [comment]
I think the issue is related to u-boot not having a supported identifier for the Raspberry CM4 module yet. So the wrong device tree blob (DTB) is loaded.

At the u-boot prompt you can issue `env print fdtfile` and it will print a loaded DTB.
```
U-Boot> env print fdtfile
fdtfile=bcm283x-rpi-other.dtb
```
The DTB should be `bcm2711-rpi-cm4.dtb`.

I believe it was added to the u-boot source [here](https://source.denx.de/u-boot/u-boot/-/commit/561bce3522bd1df5f6b10fbae5a6ea5c0b131ff9) and it was included in version 2021.04.

Unfortunately the Poky master branch only supports version 2021.01 at the moment. So you may have to wait or do your own recipe to bring in 2021.04 or apply the appropriate patches.

**Comment by agherzan** [comment]
Thanks, @havok13888 for the update.
