### ISSUE TITLE
how to disable yocto pi 4 64bit x11 in sleep mode or cpu in sleep mode ?

### ISSUE THREAD

**Issue by gitgonewithwind** [agherzan/meta-raspberrypi#923]
hi all,
sorry to bother you.
I add IMAGE_FEATURES += "x11" to my local.conf in yocto,
so I use x11 for my pi 4 touchscreen to display the chromium webpage, but after some hours, the chromium webpage become blank(white), after touch and move finger from right to left, it comes to normal display,   it seems  that  1. CPU  was in sleep mode 2. x11 or chrmoum was in sleep mode.
the most possibility is x11 was in sleep mode
 before I play maaxboard wayland, I know where I can set wayland sleep time.
but I do not know where I can disable 1. CPU sleep mode; 2 x11 sleep mode?
or some other reasons to make the chrome webpage is white blank?
any help?

Thank you very much.

**Comment by agherzan** [comment]
Your issue is not BSP specific - at least that's how it sounds to me. I've moved to Wayland for a good while. If I remember correctly there were two features in x11: screen blanking and screen saving. And both were configurable through `xset`. That's what I remember now but I'm going to close this issue and let you figure it out as a distro configuration functionality.

**Comment by wiserdivisor** [comment]
Command is:
> xset s off
